services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    container_name: backend
    volumes:
      - ./core:/usr/logic/app
    working_dir: /usr/logic/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context:  .
      dockerfile: ./dockerfiles/dev/django/Dockerfile-1 # Dockerfile برای React
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


