# Generated by Django 4.2 on 2025-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "game",
            "0004_game_first_borne_game_first_hit_game_second_borne_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="opponent_name",
            field=models.CharField(default="AI", max_length=100),
        ),
    ]
