# Generated by Django 4.2 on 2025-09-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_opponent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
