# Generated by Django 4.2 on 2025-09-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
